idf_component_register(SRCS 
                        "databus/Arduino_AVRPAR16.cpp"
                        "databus/Arduino_AVRPAR8.cpp"
                        "display/Arduino_AXS15231B.cpp"
                        "canvas/Arduino_Canvas.cpp"
                        "canvas/Arduino_Canvas_3bit.cpp"
                        "canvas/Arduino_Canvas_Indexed.cpp"
                        "canvas/Arduino_Canvas_Mono.cpp"
                        "display/Arduino_CO5300.cpp"
                        "Arduino_DataBus.cpp"
                        "display/Arduino_DSI_Display.cpp"
                        "databus/Arduino_DUEPAR16.cpp"
                        "databus/Arduino_ESP32DSIPanel.cpp"
                        "databus/Arduino_ESP32LCD16.cpp"
                        "databus/Arduino_ESP32LCD8.cpp"
                        "databus/Arduino_ESP32PAR16.cpp"
                        "databus/Arduino_ESP32PAR16Q.cpp"
                        "databus/Arduino_ESP32PAR16QQ.cpp"
                        "databus/Arduino_ESP32PAR8.cpp"
                        "databus/Arduino_ESP32PAR8Q.cpp"
                        "databus/Arduino_ESP32PAR8QQ.cpp"
                        "databus/Arduino_ESP32PAR8QQQ.cpp"
                        "databus/Arduino_ESP32QSPI.cpp"
                        "databus/Arduino_ESP32RGBPanel.cpp"
                        "databus/Arduino_ESP32S2PAR16.cpp"
                        "databus/Arduino_ESP32S2PAR16Q.cpp"
                        "databus/Arduino_ESP32S2PAR8.cpp"
                        "databus/Arduino_ESP32S2PAR8Q.cpp"
                        "databus/Arduino_ESP32SPI.cpp"
                        "databus/Arduino_ESP32SPIDMA.cpp"
                        "databus/Arduino_ESP8266SPI.cpp"
                        "Arduino_G.cpp"
                        "display/Arduino_GC9106.cpp"
                        "display/Arduino_GC9107.cpp"
                        "display/Arduino_GC9A01.cpp"
                        "Arduino_GFX.cpp"
                        "Arduino_GFX_Library.cpp"
                        "databus/Arduino_HWSPI.cpp"
                        "display/Arduino_HX8347C.cpp"
                        "display/Arduino_HX8347D.cpp"
                        "display/Arduino_HX8352C.cpp"
                        "display/Arduino_HX8357A.cpp"
                        "display/Arduino_HX8357B.cpp"
                        "display/Arduino_HX8369A.cpp"
                        "display/Arduino_ILI9225.cpp"
                        "display/Arduino_ILI9331.cpp"
                        "display/Arduino_ILI9341.cpp"
                        "display/Arduino_ILI9342.cpp"
                        "display/Arduino_ILI9481_18bit.cpp"
                        "display/Arduino_ILI9486.cpp"
                        "display/Arduino_ILI9486_18bit.cpp"
                        "display/Arduino_ILI9488.cpp"
                        "display/Arduino_ILI9488_18bit.cpp"
                        "display/Arduino_ILI9488_3bit.cpp"
                        "display/Arduino_ILI9806.cpp"
                        "display/Arduino_JBT6K71.cpp"
                        "display/Arduino_JD9613.cpp"
                        "databus/Arduino_mbedSPI.cpp"
                        "databus/Arduino_NRFXSPI.cpp"
                        "display/Arduino_NT35310.cpp"
                        "display/Arduino_NT35510.cpp"
                        "display/Arduino_NT39125.cpp"
                        "display/Arduino_NV3023.cpp"
                        "display/Arduino_NV3041A.cpp"
                        "display/Arduino_OTM8009A.cpp"
                        "display/Arduino_R61529.cpp"
                        "display/Arduino_RGB_Display.cpp"
                        "display/Arduino_RM67162.cpp"
                        "display/Arduino_RM690B0.cpp"
                        "databus/Arduino_RPiPicoPAR16.cpp"
                        "databus/Arduino_RPiPicoPAR8.cpp"
                        "databus/Arduino_RPiPicoSPI.cpp"
                        "databus/Arduino_RTLPAR8.cpp"
                        "display/Arduino_SEPS525.cpp"
                        "display/Arduino_SH1106.cpp"
                        "display/Arduino_SSD1283A.cpp"
                        "display/Arduino_SSD1306.cpp"
                        "display/Arduino_SSD1331.cpp"
                        "display/Arduino_SSD1351.cpp"
                        "display/Arduino_ST7735.cpp"
                        "display/Arduino_ST7789.cpp"
                        "display/Arduino_ST77916.cpp"
                        "display/Arduino_ST7796.cpp"
                        "databus/Arduino_STM32PAR8.cpp"
                        "databus/Arduino_SWPAR16.cpp"
                        "databus/Arduino_SWPAR8.cpp"
                        "databus/Arduino_SWSPI.cpp"
                        "Arduino_TFT.cpp"
                        "Arduino_TFT_18bit.cpp"
                        "databus/Arduino_UNOPAR8.cpp"
                        "display/Arduino_WEA2012.cpp"
                        "databus/Arduino_Wire.cpp"
                        "databus/Arduino_XL9535SWSPI.cpp"
                        "databus/Arduino_XCA9554SWSPI.cpp"
                      INCLUDE_DIRS "."
                      REQUIRES arduino-esp32
                      )
                      
target_compile_options(${COMPONENT_LIB} PRIVATE -Wno-error=overloaded-virtual)